from typing import TypedDict, List, Dict, Any

class AgentState(TypedDict):
    """
    Shared graph state object passed across nodes in the LangGraph multi-agent pipeline.
    Represents the unified context of an enterprise query analysis.
    """
    # Inputs & Intermediate Processing
    query: str                          # Original user query
    query_expanded: str                 # Expanded query with terms generated by Query Understander
    documents: List[Dict[str, Any]]     # List of retrieved document chunks with similarity scores
    compressed_context: str             # High-relevance, merged knowledge base summary
    session_id: str                     # Isolated session namespace ID (prevents cross-user contamination)
    
    # Synthesis & Strategy
    reasoning_summary: str              # Step-by-step logic, comparative analyses, and trade-offs
    
    # Security, Compliance, & Trust Audit
    citations: List[Dict[str, Any]]     # References mapping claims in the response back to raw chunk sources
    governance_report: Dict[str, Any]   # Dict containing citation coverage, contradiction analysis, etc.
    confidence_score: float             # Trust percentage score between 0.0 and 1.0
    
    # Visual Tracking & Analytics
    execution_trace: List[Dict[str, Any]] # Sequential logs for visual rendering of active states
    node_latency_metrics: Dict[str, float] # Time elapsed per node (seconds/milliseconds)
    
    # Final Output
    final_response: str                 # Unified response structured for executive presentation
